### ISSUE TITLE
linux上安装失败

### ISSUE THREAD

**Issue by xinggu** [CTPPlus/AlgoPlus#3]
aliyun centos 7:

ERROR: Command errored out with exit status 1:
     command: /usr/local/bin/python3.7 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-h3mrfnuv/AlgoPlus/setup.py'"'"'; __file__='"'"'/tmp/pip-install-h3mrfnuv/AlgoPlus/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base pip-egg-info
         cwd: /tmp/pip-install-h3mrfnuv/AlgoPlus/
    Complete output (11 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-h3mrfnuv/AlgoPlus/setup.py", line 68, in <module>
        compiler_directives={'language_level': 3, "binding": True}
      File "/usr/local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 966, in cythonize
        aliases=aliases)
      File "/usr/local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 810, in create_extension_list
        for file in nonempty(sorted(extended_iglob(filepattern)), "'%s' doesn't match any files" % filepattern):
      File "/usr/local/lib/python3.7/site-packages/Cython/Build/Dependencies.py", line 109, in nonempty
        raise ValueError(error_msg)
    ValueError: '/tmp/pip-install-h3mrfnuv/src/AlgoPlus/CTP/MdApi.pyx' doesn't match any files
    ----------------------------------------
ERROR: Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.

是什么情况？谢谢～

**Comment by CTPPlus** [comment]
linux系统中修改修改两行代码之后再编译安装：AlgoPlus/src/AlgoPlus/CTP/c2cython/MyTools.h，第18行添加注释，第19行取消注释。用linux的朋友越来越多了，周末做一个教程。

**Comment by xinggu** [comment]
谢谢你的及时回复，我第一遍是用的pip尝试直接装，报错。刚才又下载了然后按你说的改了以后再用python setup.py install装，还是报错:
python setup.py install
running install
running bdist_egg
running egg_info
creating AlgoPlus.egg-info
writing AlgoPlus.egg-info/PKG-INFO
writing dependency_links to AlgoPlus.egg-info/dependency_links.txt
writing top-level names to AlgoPlus.egg-info/top_level.txt
writing manifest file 'AlgoPlus.egg-info/SOURCES.txt'
error: package directory 'AlgoPlus' does not exist

**Comment by CTPPlus** [comment]
这完全是我的锅，发布项目的时候，为了目录整洁，我把setup.py放在tools文件夹里了，明天下午你再来看一下，我把linux文件、教程做好。

**Comment by xinggu** [comment]
谢谢，那我期待明天的linux版了

**Comment by CTPPlus** [comment]
已增加linux系统编译安装工具。可参考https://7jia.com/71002.html安装。

**Comment by xinggu** [comment]
好，我试了一下，卡在anaconda这里一动不动：
Unpacking payload ...
  0%|                                                                                                                                      | 0/291 [00:00<?, ?it/s]
anaconda是必须的吗？

**Comment by CTPPlus** [comment]
我用ubuntu安装没有问题，centos我找个环境试一下。不用anaconda也可以，直接装python，只需要安装Cython就可以了。

**Comment by xinggu** [comment]
我试了，那个sh文件安装报错说cython.Build not found.不过刚才我直接python setup.py install安装成功了。待试用一下看看效果。
